name: CI with Docker and SonarCloud

on:

  workflow_dispatch:

jobs:
 
  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2.0.2
      with:
          username: ${{ secrets.SONARCLOUD_USERNAME }}
          password: ${{ secrets.SONARCLOUD_TOKEN }}
    - name: Build the Docker Image
      run: docker build . --file Dockerfile --tag hello-world-war:latest  
    - name: Eun & Test Container
      run: docker run -itd --name node_hello -p 3000:3000  node_hello:latest
    - run: sleep 5 && curl localhost:3000
    - name: Retagging the Image 
      run: docker tag node_hello:latest ddriham/node-hello:latest
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: docker push
      run: docker push ddriham/node-hello:latest
